"use client";
import Navbar from '@/components/Navbar';
import './globals.css';
import { Inter } from 'next/font/google';
import { useEffect, useState } from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Balaji Mhetre | Protfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  const [scrollTop, setScrollTop] = useState(0);

  const onScroll = () => {
    const winScroll = document.documentElement.scrollTop;
    const height =
      document.documentElement.scrollHeight -
      document.documentElement.clientHeight;

    const scrolled = (winScroll / height) * 100;

    setScrollTop(scrolled);
  };

  useEffect(() => {
    window.addEventListener("scroll", onScroll);

    return () => window.removeEventListener("scroll", onScroll);
  }, []);

  return (
    <>
      <html lang="en">
        <body className={inter.className}>
          <div className="progressMainWrapper">
            <div
              className="progressMainStyle"
              style={{ width: `${scrollTop}%` }}
            ></div>
          </div>
          <Navbar />
          {children}
        </body>
      </html>
    </>
  );
}
